### ISSUE TITLE
BUG - Javascript error on certain seeds.

### ISSUE THREAD

**Issue by snake0484** [TwoAbove/noita-tools#200]
2589476

## To Reproduce
Goto Seed info with the seed above

## Stacktrace
TypeError: Cannot read properties of undefined (reading 'min')
    at A.apply_random_variable (504.ed7b5e6a.chunk.js:1:590937)
    at A.get_gun_data (504.ed7b5e6a.chunk.js:1:589787)
    at A.provide (504.ed7b5e6a.chunk.js:1:594093)
    at l.generate_shop_wand (504.ed7b5e6a.chunk.js:1:42396)
    at l.spawn_all_shop_items (504.ed7b5e6a.chunk.js:1:42965)
    at l.provideLevel (504.ed7b5e6a.chunk.js:1:43225)
    at l.test (504.ed7b5e6a.chunk.js:1:43468)
    at o.check (504.ed7b5e6a.chunk.js:1:599071)
    at 504.ed7b5e6a.chunk.js:1:599542
    at Array.every (<anonymous>)

## Additional context
I know a logged a similar looking one earlier today but this has a different stacktrace so im guessing its separate.
This was found when I searched for Shop: Tau and Circle of vigor (cause im a scrub, also love the new UI) on the search but is reproable on the seed info page.

Update: the seed it found using the above search criteria wasn't actually a spell shop so that might not be working as intended.

Going to revive this for each seed I find that doesn't work and remove the ones that do

**Comment by TwoAbove** [comment]
Thanks! I'll take a look this evening

**Comment by TwoAbove** [comment]
@snake0484 Fix will be out in ~15 mins

**Comment by snake0484** [comment]
Yep, its fixed!
