### ISSUE TITLE
BUG - Errors when running in debug mode

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#223]
When I run the project in debug mode via `yarn dev-win` I see two errors:

1. `Error: Invalid accountId or applicationKeyId`
2. `TypeError: Cannot read properties of undefined (reading 'data')`

This does not stop the project from starting. They are non-blocking errors.

Full log with unrelated compilation warnings removed:

```text
C:\Users\Daniel\AppData\Roaming\npm\yarn.cmd dev-win
[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./server`
Running at http://localhost:3001

Error: Invalid accountId or applicationKeyId
    at exports.getAuthHeaderObject (c:\Users\Daniel\Documents\source\noita-tools\node_modules\backblaze-b2\lib\utils.js:18:15)
    at getRequestOptions (c:\Users\Daniel\Documents\source\noita-tools\node_modules\backblaze-b2\lib\actions\auth.js:23:24)
    at exports.authorize (c:\Users\Daniel\Documents\source\noita-tools\node_modules\backblaze-b2\lib\actions\auth.js:10:9)
    at B2.authorize (c:\Users\Daniel\Documents\source\noita-tools\node_modules\backblaze-b2\lib\b2.js:31:25)
    at authorize (c:\Users\Daniel\Documents\source\noita-tools\server\index.js:87:15)
    at Object.<anonymous> (c:\Users\Daniel\Documents\source\noita-tools\server\index.js:89:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
TypeError: Cannot read properties of undefined (reading 'data')
    at upload (c:\Users\Daniel\Documents\source\noita-tools\server\index.js:185:16)
    at process.<anonymous> (c:\Users\Daniel\Documents\source\noita-tools\server\index.js:203:15)
    at process.emit (c:\Users\Daniel\Documents\source\noita-tools\lib\events.js:527:28)
    at process._fatalException (c:\Users\Daniel\Documents\source\noita-tools\lib\internal\process\execution.js:167:25)
    at processPromiseRejections (c:\Users\Daniel\Documents\source\noita-tools\lib\internal\process\promises.js:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {stack: 'TypeError: Cannot read properties of undefine…ons (node:internal/process/task_queues:96:32)', message: 'Cannot read properties of undefined (reading 'data')'}
Gracefully shut down

[nodemon] clean exit - waiting for changes before restart
[HPM] Proxy created: /api/**  -> http://localhost:3001/
[HPM] Proxy created: /socket.io/**  -> http://localhost:3001/
Starting the development server...
Compiled with warnings.

...

webpack compiled with 19 warnings
No issues found.

```

**Comment by TwoAbove** [comment]
The route is now conditional, so you shouldn't get these
