### ISSUE TITLE
BUG - Page goes blank in seed 1536514934 when switching to advanced

### ISSUE THREAD

**Issue by x0rsw1tch** [TwoAbove/noita-tools#232]
## To Reproduce

1. Open Noitool
2. Open seed `1536514934`
3. Switch to advanced mode
4. Page goes blank with several repeating JS errors in console

```
main.84c4cd7d.js:1 TypeError: Cannot read properties of undefined (reading 'find')
    at q (HolyMountain.tsx:135:34)
    at bi (main.84c4cd7d.js:1:78718)
    at Ps (main.84c4cd7d.js:1:99657)
    at bl (main.84c4cd7d.js:1:137121)
    at vu (main.84c4cd7d.js:1:125134)
    at yu (main.84c4cd7d.js:1:125062)
    at hu (main.84c4cd7d.js:1:124925)
    at ru (main.84c4cd7d.js:1:121709)
    at iu (main.84c4cd7d.js:1:122100)
    at Ko (main.84c4cd7d.js:1:62885)
```

**Comment by TwoAbove** [comment]
Thanks! Will make a fix asap

**Comment by TwoAbove** [comment]
@x0rsw1tch Fix should be out in a few minutes
